### ISSUE TITLE
Fails building roscpp - xmlrpc linker error

### ISSUE THREAD

**Issue by yamokosk** [kyonifer/ros-macports#9] opened 2013-12-18 19:08 UTC
roscpp fails to build. The error is below:

```
:notice:build --->  Building ros-hydro-roscpp
:debug:build Executing org.macports.build (ros-hydro-roscpp)
:info:build [  6%] [ 21%] [ 23%] Built target roscpp_generate_messages_lisp
:info:build Built target roscpp_generate_messages_py
:info:build Built target roscpp_generate_messages_cpp
:info:build [ 23%] [ 23%] Built target roscpp_gencpp
:info:build Built target roscpp_generate_messages
:info:build Linking CXX shared library ../../devel_isolated/roscpp/lib/libroscpp.dylib
:info:build Undefined symbols for architecture x86_64:
:info:build   "XmlRpc::XmlRpcServerMethod::XmlRpcServerMethod(std::string const&, XmlRpc::XmlRpcServer*)", referenced from:
:info:build       ros::XMLRPCCallWrapper::XMLRPCCallWrapper(std::string const&, boost::function<void (XmlRpc::XmlRpcValue&, XmlRpc::XmlRpcValue&)> const&, XmlRpc::XmlRpcServer*) in xmlrpc_manager.cpp.o
:info:build ld: symbol(s) not found for architecture x86_64
:info:build clang: error: linker command failed with exit code 1 (use -v to see invocation)
:info:build make[2]: *** [../../devel_isolated/roscpp/lib/libroscpp.dylib] Error 1
:info:build make[1]: *** [CMakeFiles/roscpp.dir/all] Error 2
:info:build make: *** [all] Error 2
```

**Comment by venabled** [comment] 2013-12-18 20:41
Do you have   ros-hydro-xmlrpcpp @1.0.0_0 (active) installed? Im wondering if we missed a rosdep somewhere.

**Comment by yamokosk** [comment] 2013-12-19 22:22
Looks like I do. Anything else to check?

```
$ sudo port install ros-hydro-xmlrpcpp
--->  Computing dependencies for ros-hydro-xmlrpcpp
--->  Cleaning ros-hydro-xmlrpcpp
--->  Updating database of binaries: 100.0%
--->  Scanning binaries for linking errors: 100.0%
--->  No broken files found.
```

**Comment by venabled** [comment] 2013-12-19 22:36
Can you hit me with a: 

`$ otool -L /opt/local/lib/libxmlrpcpp.dylib`

Mine looks like: 

```
/opt/local/lib/libxmlrpcpp.dylib:
/opt/local/lib/libxmlrpcpp.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

I'm wondering if this is one of the magical C++11 issues we've been having.

**Comment by yamokosk** [comment] 2013-12-20 17:49
Looks like some difference in std c++

```
$ otool -L /opt/local/lib/libxmlrpcpp.dylib
/opt/local/lib/libxmlrpcpp.dylib:
/opt/local/lib/libxmlrpcpp.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 65.1.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
```

**Comment by venabled** [comment] 2013-12-20 19:10
Did you do this in stages? Maybe try removing all the ros stuff and rebuilding.

**Comment by yamokosk** [comment] 2013-12-20 20:08
I uninstalled everything to do with ROS:

```
$ sudo port installed | grep ros
$
```

Then I did a fresh install of ros-hydro-roslaunch. If failed to build, here is the offending section of the log file:

```
:info:build In file included from /opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/src/libros/service.cpp:29:
:info:build In file included from /opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/include/ros/connection.h:41:
:info:build In file included from /opt/local/include/boost/signals.hpp:9:
:info:build /opt/local/include/boost/signal.hpp:17:4: warning: "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING." [-W#warnings]
:info:build #  warning                  "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING."
:info:build    ^
:info:build 1 warning generated.
:info:build Linking CXX shared library ../../devel_isolated/roscpp/lib/libroscpp.dylib
:info:build Undefined symbols for architecture x86_64:
:info:build   "XmlRpc::XmlRpcServerMethod::XmlRpcServerMethod(std::string const&, XmlRpc::XmlRpcServer*)", referenced from:
:info:build       ros::XMLRPCCallWrapper::XMLRPCCallWrapper(std::string const&, boost::function<void (XmlRpc::XmlRpcValue&, XmlRpc::XmlRpcValue&)> const&, XmlRpc::XmlRpcServer*) in xmlrpc_manager.cpp.o
:info:build ld: symbol(s) not found for architecture x86_64
:info:build clang: error: linker command failed with exit code 1 (use -v to see invocation)
:info:build make[2]: *** [../../devel_isolated/roscpp/lib/libroscpp.dylib] Error 1
:info:build make[1]: *** [CMakeFiles/roscpp.dir/all] Error 2
:info:build make: *** [all] Error 2
:info:build Base path: /Users/jyamokos/src/ros-macports/hydro/ros-hydro-xmlrpcpp
:info:build Source space: /opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0
:info:build Build space: /opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated
:info:build Devel space: /opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/devel_isolated
:info:build Install space: /opt/local
:info:build Additional CMake Arguments: -DCMAKE_SKIP_RPATH:BOOL=OFF -DCMAKE_INSTALL_NAME_DIR:STRING=/opt/local/lib -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON -DSETUPTOOLS_DEB_LAYOUT=OFF -DPYTHON_EXECUTABLE:FILEPATH=/opt/local/bin/python2.7
:info:build ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:info:build ~~  traversing 1 packages in topological order:
:info:build ~~  - roscpp
:info:build ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:info:build ESC]2;roscpp [1 of 1]^G==> Processing catkin package: 'roscpp'
:info:build Makefile exists, skipping explicit cmake invocation...
:info:build ==> make cmake_check_build_system in '/opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated/roscpp' with '_CATKIN_SETUP_DIR=/opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/destroot/opt/local'
:info:build -- Using CATKIN_DEVEL_PREFIX: /opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/devel_isolated/roscpp
:info:build -- Using CMAKE_PREFIX_PATH: /opt/local;/opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/destroot/opt/local/lib
:info:build -- This workspace overlays: /opt/local
:info:build -- Using default Python package layout
:info:build -- Using CATKIN_ENABLE_TESTING: ON
:info:build -- Call enable_testing()
:info:build -- Using CATKIN_TEST_RESULTS_DIR: /opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated/roscpp/test_results
:info:build -- Found gtest: gtests will be built
:info:build CMake Warning at /opt/local/share/catkin/cmake/test/nosetests.cmake:94 (message):
:info:build   nosetests not found, Python tests can not be run (try installing package
:info:build   'python-nose')
:info:build Call Stack (most recent call first):
:info:build   /opt/local/share/catkin/cmake/all.cmake:134 (include)
:info:build   /opt/local/share/catkin/cmake/catkinConfig.cmake:20 (include)
:info:build   CMakeLists.txt:4 (find_package)
:info:build 
:info:build 
:info:build -- catkin 0.5.77
:info:build -- Boost version: 1.55.0
:info:build -- Found the following Boost libraries:
:info:build --   signals
:info:build --   filesystem
:info:build --   system
:info:build -- roscpp: 1 messages, 3 services
:info:build -- Configuring done
:info:build -- Generating done
:info:build -- Build files have been written to: /opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated/roscpp
:info:build ==> make -j4 -l4 in '/opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated/roscpp'
:info:build <== Failed to process package 'roscpp': 
:info:build   Command 'make -j4 -l4' returned non-zero exit status 2
:info:build 
:info:build Reproduce this error by running:
:info:build ==> cd /opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated/roscpp && make -j4 -l4
:info:build 
:info:build Command failed, exiting.
:info:build Command failed: DESTDIR=/opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/destroot /opt/local/bin/catkin_make_isolated  --source /opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0  --build /opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated  --devel /opt/local/var/macports/build/_Users_jyamokos_src_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/devel_isolated  -DCMAKE_SKIP_RPATH:BOOL=OFF  -DCMAKE_INSTALL_NAME_DIR:STRING=/opt/local/lib  -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON  -DSETUPTOOLS_DEB_LAYOUT=OFF  -DPYTHON_EXECUTABLE:FILEPATH=/opt/local/bin/python2.7  --install-space=/opt/local  --install
:info:build Exit code: 1
:error:build org.macports.build for port ros-hydro-roscpp returned: command execution failed
:debug:build Error code: NONE
:debug:build Backtrace: command execution failed
    while executing
"$procedure $targetname"
:info:build Warning: targets not executed for ros-hydro-roscpp: org.macports.activate org.macports.build org.macports.destroot org.macports.install
:error:build Failed to install ros-hydro-roscpp
:debug:build could not read "/opt/local/share/xmlrpcpp/package.xml": no such file or directory
    while executing
"::file type $file"
```

For completeness here is everything I had installed before installing roslaunch,

```
$ port installed
The following ports are currently installed:
  apr @1.4.8_0 (active)
  apr-util @1.5.2_1 (active)
  boost @1.55.0_0+no_single+no_static+python27 (active)
  bzip2 @1.0.6_0 (active)
  cmake @2.8.12_2 (active)
  cppunit @1.12.1_0 (active)
  curl-ca-bundle @7.33.0_0 (active)
  db46 @4.6.21_8 (active)
  db_select @0.1_2 (active)
  dbus @1.6.12_0+startupitem (active)
  dbus-glib @0.100.2_0 (active)
  dbus-python27 @0.84.0_0 (active)
  desktop-file-utils @0.15_1 (active)
  dirac @1.0.2_1 (active)
  eigen3 @3.2.0_0+cmake (active)
  enca @1.13_0 (active)
  expat @2.1.0_0 (active)
  ffmpeg @2.1.1_0+gpl2 (active)
  fftw-3 @3.3.3_5 (active)
  fontconfig @2.11.0_0 (active)
  freetype @2.5.2_0 (active)
  fribidi @0.19.6_1 (active)
  gdbm @1.10_2 (active)
  gettext @0.18.3.1_1 (active)
  glib2 @2.38.2_0 (active)
  gmp @5.1.2_0 (active)
  gnutls @3.1.10_1 (active)
  icu @51.2_1 (active)
  ilmbase @1.0.2_0 (active)
  jasper @1.900.1_10 (active)
  jbigkit @2.0_2 (active)
  jpeg @9_1 (active)
  lame @3.99.5_0 (active)
  lcms @1.19_5 (active)
  lcms2 @2.4_2 (active)
  libass @0.10.1_0 (active)
  libbluray @0.3.0_0 (active)
  libedit @20121213-3.0_0 (active)
  libffi @3.0.13_0 (active)
  libiconv @1.14_0 (active)
  libidn @1.26_0 (active)
  libmng @1.0.10_3 (active)
  libmodplug @0.8.8.4_0 (active)
  libogg @1.3.1_0 (active)
  libopus @1.1_0 (active)
  libpng @1.5.17_0 (active)
  libsdl @1.2.15_3+x11 (active)
  libtasn1 @2.11_0 (active)
  libtheora @1.1.1_1 (active)
  libvorbis @1.3.3_0 (active)
  libvpx @1.2.0_1 (active)
  libxml2 @2.9.1_0 (active)
  libxslt @1.1.28_0 (active)
  libyaml @0.1.4_1 (active)
  ncurses @5.9_2 (active)
  nettle @2.6_1 (active)
  nosetests_select @0.1_0 (active)
  opencv @2.4.7_1+opencl+python27+qt4 (active)
  openexr @1.7.0_0 (active)
  openjpeg15 @1.5.0_0 (active)
  openssl @1.0.1e_1 (active)
  orc @0.4.18_0 (active)
  p11-kit @0.20.1_0 (active)
  perl5 @5.12.4_0+perl5_12 (active)
  perl5.12 @5.12.4_3 (active)
  pkgconfig @0.28_0 (active)
  popt @1.16_0 (active)
  py27-catkin-pkg @0.1.20_0 (active)
  py27-crypto @2.6.1_1 (active)
  py27-empy @3.3_1 (active)
  py27-gobject @2.28.6_0 (active)
  py27-netifaces @0.8_0 (active)
  py27-nose @1.3.0_0 (active)
  py27-numpy @1.8.0_2 (active)
  py27-paramiko @1.11.2_0 (active)
  py27-pil @1.1.7_7 (active)
  py27-pyqt4 @4.10.3_2 (active)
  py27-setuptools @2.0.1_0 (active)
  py27-sip @4.15.3_0 (active)
  py27-tkinter @2.7.6_0 (active)
  py27-yaml @3.10_2 (active)
  python27 @2.7.6_0 (active)
  python_select @0.3_3 (active)
  qt4-mac @4.8.5_0 (active)
  schroedinger @1.0.11_0 (active)
  speex @1.2rc1_0 (active)
  sqlite3 @3.8.2_0 (active)
  tcl @8.6.1_0+corefoundation+threads (active)
  tiff @4.0.3_2 (active)
  tinyxml @2.6.2_2 (active)
  tk @8.6.1_1+quartz (active)
  x264 @20130823_0 (active)
  xmlrpcxx @0.7_0
  xorg-kbproto @1.0.6_0 (active)
  xorg-libpthread-stubs @0.3_0 (active)
  xorg-libX11 @1.6.2_0 (active)
  xorg-libXau @1.0.8_0 (active)
  xorg-libxcb @1.9.1_0+python27 (active)
  xorg-libXdmcp @1.1.1_0 (active)
  xorg-libXext @1.3.2_0 (active)
  xorg-libXrandr @1.4.2_0 (active)
  xorg-randrproto @1.4.0_0 (active)
  xorg-renderproto @0.11.1_0 (active)
  xorg-xcb-proto @1.8_0+python27 (active)
  xorg-xextproto @7.2.99.901_0 (active)
  xorg-xproto @7.0.24_0 (active)
  xrender @0.9.8_0 (active)
  XviD @1.3.2_3 (active)
  xz @5.0.5_0 (active)
  zlib @1.2.8_0 (active)
```

**Comment by yamokosk** [comment] 2013-12-21 18:34
Tried looking at the error more in-depth. Its certainly not lying. Specifically, it breaks linking ros-hydro-cpp with the message:

```
:info:build Undefined symbols for architecture x86_64:
:info:build   "XmlRpc::XmlRpcServerMethod::XmlRpcServerMethod(std::string const&, XmlRpc::XmlRpcServer*)", referenced from:
:info:build       ros::XMLRPCCallWrapper::XMLRPCCallWrapper(std::string const&, boost::function<void (XmlRpc::XmlRpcValue&, XmlRpc::XmlRpcValue&)> const&, XmlRpc::XmlRpcServer*) in xmlrpc_manager.cpp.o
```

So I searched libxmlrpcpp.dylib for that symbol and got (pushed through http://demangler.com, of course)

```
$ nm -n -arch x86_64 libxmlrpcpp.dylib | grep XmlRpcServerMethod
```

Demangled output (only pasted XmlRpcServer constructors and class methods), and the method is definitely being exported (x1add0):

```
000000000000a1c0 T _XmlRpc::XmlRpcServer::addMethod(XmlRpc::XmlRpcServerMethod*)
000000000000a210 T _XmlRpc::XmlRpcServer::removeMethod(XmlRpc::XmlRpcServerMethod*)
000000000000c920 T _XmlRpc::XmlRpcServerMethod::name()
000000000001add0 T _XmlRpc::XmlRpcServerMethod::XmlRpcServerMethod(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, XmlRpc::XmlRpcServer*)
000000000001af30 T _XmlRpc::XmlRpcServerMethod::~XmlRpcServerMethod()
000000000001af80 T _XmlRpc::XmlRpcServerMethod::~XmlRpcServerMethod()
000000000001afa0 T _XmlRpc::XmlRpcServerMethod::~XmlRpcServerMethod()
000000000001b040 T _XmlRpc::XmlRpcServerMethod::help()
000000000003e560 S _typeinfo name for XmlRpc::XmlRpcServerMethod
0000000000044b10 S _vtable for XmlRpc::XmlRpcServerMethod
0000000000044b40 S _typeinfo for XmlRpc::XmlRpcServerMethod
```

I then checked  dylib path and looks like /opt/local/lib is in there.. Not sure if it matters, but here is my xcode version:

```
$ xcodebuild -version
Xcode 5.0.2
Build version 5A3005
$ clang --version
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin12.4.1
Thread model: posix
```

**Comment by venabled** [comment] 2013-12-23 19:12
Can you uninstall  xmlrpcxx @0.7_0 before trying again?

**Comment by venabled** [comment] 2013-12-23 19:13
There's definitely something broken with how it's linking against XmlRpc. I can't replicate this from a relatively clean build of ros-hydro with all my updated ports, so my best guess is that there's something conflicting (in your case, xmlrpcxx) that we need to add to the conflicts-with line in the Portfile.

**Comment by yamokosk** [comment] 2013-12-24 01:25
Sorry, I completely missed the xmlrpcxx port. Well I removed it as well as all the ros ports, reinstalled ros-hydro-roscpp and it still fails.. in the same way.

I am thinking that something is up with the linker even finding the library. Can "VERBOSE=1" be passed to cmake? I could inspect the linker command to see if the correct paths are being used.

**Comment by yamokosk** [comment] 2013-12-24 15:31
Don't know why I haven't noticed this before, but could this be my problem:

```
$ sudo port install ros-hydro-roscpp
dyld: DYLD_ environment variables being ignored because main executable (/usr/bin/sudo) is setuid or setgid
```

This is a known bug introduced in 10.8 (http://openradar.appspot.com/11894054). So if DYLD vars are being ignored, how is the library ever being found??

**Comment by yamokosk** [comment] 2013-12-24 16:08
Ok, I am stuck. Looks like the correct library is being linked in, regardless of that DYLD_\* warning. I couldn't figure out how to pass 'VERBOSE=1' through port, so I cd'ed into the build directory and ran make manually. I spaced out the linking step to make it easier to read:

```
$ make VERBOSE=1
...
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/roscpp.dir/link.txt --verbose=1 /usr/bin/clang++   -dynamiclib -Wl,-headerpad_max_install_names -o ../../devel_isolated/roscpp/lib/libroscpp.dylib -install_name /opt/local/lib/libroscpp.dylib 

CMakeFiles/roscpp.dir/src/libros/master.cpp.o 

CMakeFiles/roscpp.dir/src/libros/network.cpp.o 

CMakeFiles/roscpp.dir/src/libros/subscriber.cpp.o 

CMakeFiles/roscpp.dir/src/libros/common.cpp.o 

CMakeFiles/roscpp.dir/src/libros/publisher_link.cpp.o 

CMakeFiles/roscpp.dir/src/libros/service_publication.cpp.o 

CMakeFiles/roscpp.dir/src/libros/connection.cpp.o 

CMakeFiles/roscpp.dir/src/libros/single_subscriber_publisher.cpp.o 

CMakeFiles/roscpp.dir/src/libros/param.cpp.o 

CMakeFiles/roscpp.dir/src/libros/service_server.cpp.o 

CMakeFiles/roscpp.dir/src/libros/wall_timer.cpp.o 

CMakeFiles/roscpp.dir/src/libros/xmlrpc_manager.cpp.o 

CMakeFiles/roscpp.dir/src/libros/publisher.cpp.o 

CMakeFiles/roscpp.dir/src/libros/timer.cpp.o 

CMakeFiles/roscpp.dir/src/libros/io.cpp.o 

CMakeFiles/roscpp.dir/src/libros/names.cpp.o 

CMakeFiles/roscpp.dir/src/libros/topic.cpp.o 

CMakeFiles/roscpp.dir/src/libros/topic_manager.cpp.o 

CMakeFiles/roscpp.dir/src/libros/poll_manager.cpp.o 

CMakeFiles/roscpp.dir/src/libros/publication.cpp.o 

CMakeFiles/roscpp.dir/src/libros/intraprocess_subscriber_link.cpp.o 

CMakeFiles/roscpp.dir/src/libros/intraprocess_publisher_link.cpp.o 

CMakeFiles/roscpp.dir/src/libros/callback_queue.cpp.o 

CMakeFiles/roscpp.dir/src/libros/service_server_link.cpp.o 

CMakeFiles/roscpp.dir/src/libros/service_client.cpp.o 

CMakeFiles/roscpp.dir/src/libros/node_handle.cpp.o 

CMakeFiles/roscpp.dir/src/libros/connection_manager.cpp.o 

CMakeFiles/roscpp.dir/src/libros/file_log.cpp.o 

CMakeFiles/roscpp.dir/src/libros/transport/transport_udp.cpp.o 

CMakeFiles/roscpp.dir/src/libros/transport/transport_tcp.cpp.o 

CMakeFiles/roscpp.dir/src/libros/subscriber_link.cpp.o 

CMakeFiles/roscpp.dir/src/libros/service_client_link.cpp.o 

CMakeFiles/roscpp.dir/src/libros/transport_publisher_link.cpp.o 

CMakeFiles/roscpp.dir/src/libros/transport_subscriber_link.cpp.o 

CMakeFiles/roscpp.dir/src/libros/service_manager.cpp.o 

CMakeFiles/roscpp.dir/src/libros/rosout_appender.cpp.o 

CMakeFiles/roscpp.dir/src/libros/init.cpp.o 

CMakeFiles/roscpp.dir/src/libros/subscription.cpp.o CMakeFiles/roscpp.dir/src/libros/subscription_queue.cpp.o 

CMakeFiles/roscpp.dir/src/libros/spinner.cpp.o 

CMakeFiles/roscpp.dir/src/libros/internal_timer_manager.cpp.o 

CMakeFiles/roscpp.dir/src/libros/message_deserializer.cpp.o 

CMakeFiles/roscpp.dir/src/libros/header.cpp.o CMakeFiles/roscpp.dir/src/libros/poll_set.cpp.o 

CMakeFiles/roscpp.dir/src/libros/service.cpp.o CMakeFiles/roscpp.dir/src/libros/this_node.cpp.o 

/opt/local/lib/libcpp_common.dylib 

/opt/local/lib/librosconsole.dylib 

/opt/local/lib/libboost_regex-mt.dylib 

/opt/local/lib/libboost_thread-mt.dylib 

/opt/local/lib/liblog4cxx.dylib 

/opt/local/lib/librostime.dylib 

/opt/local/lib/libboost_date_time-mt.dylib 

/opt/local/lib/libboost_system-mt.dylib 

/opt/local/lib/libroscpp_serialization.dylib 

/opt/local/lib/libxmlrpcpp.dylib 

/opt/local/lib/libboost_signals-mt.dylib /opt/local/lib/libboost_filesystem-mt.dylib 

/opt/local/lib/libboost_system-mt.dylib /opt/local/lib/libroscpp_serialization.dylib 

/opt/local/lib/libxmlrpcpp.dylib 

/opt/local/lib/libboost_signals-mt.dylib /opt/local/lib/libboost_filesystem-mt.dylib 
```

So again.. not sure what is going on... The only strangeness is that it is being included twice. But since those are the same files, that shouldn't be a problem.

```
$ ls -la /opt/local/lib/libxmlrpcpp.dylib
-rwxr-xr-x  1 macports  admin  382616 Dec 24 09:48 /opt/local/lib/libxmlrpcpp.dylib
```

**Comment by kyonifer** [comment] 2014-01-01 18:58
I just rebuilt roscpp on a clean install of Mavericks and wasn't able to reproduce. Are you running latest XCode on Mavericks?

**Comment by jf---** [comment] 2014-01-02 00:34
Hi,

Thanks for the hard work making ROS happen on OSX.
I'm just getting started installing through macports ( pretty impressed how smooth things ran thusfar, considering the enormity of ROS ) and the process halted precisely at the 

```
:info:build Undefined symbols for architecture x86_64:
:info:build   "XmlRpc::XmlRpcServerMethod::XmlRpcServerMethod(std::string const&, XmlRpc::XmlRpcServer*)", referenced from:
:info:build       ros::XMLRPCCallWrapper::XMLRPCCallWrapper(std::string const&, boost::function<void (XmlRpc::XmlRpcValue&, XmlRpc::XmlRpcValue&)> const&, XmlRpc::XmlRpcServer*) in xmlrpc_manager.cpp.o
```

issue. Another pair of eyes reporting for duty ;)

**Comment by kyonifer** [comment] 2014-01-02 10:38
jf, what version of OS X/XCode are you on?

**Comment by jf---** [comment] 2014-01-02 11:52
XCode 5.0.0 OSX 10.8.5

I guess you're interested to know which compiler I'm using?

$ port select --list gcc
Available versions for gcc:
    llvm-gcc42 (active)
    mp-gcc44
    mp-gcc45
    mp-gcc48
    none

$ which llvm-gcc-4.2 
/usr/bin/llvm-gcc-4.2

**Comment by jf---** [comment] 2014-01-02 12:32
Upgraded XCode to 5.0.2, pretty much the same thing still

$ cd /opt/local/var/macports/build/_Users_jelleferinga_GIT_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated/roscpp && make -j8 -l8
[100%] Built target roscpp_generate_messages_py
[100%] [100%] Built target roscpp_generate_messages_lisp
Built target roscpp_generate_messages_cpp
[100%] [100%] Built target roscpp_generate_messages
Built target roscpp_gencpp
Linking CXX shared library ../../devel_isolated/roscpp/lib/libroscpp.dylib
Undefined symbols for architecture x86_64:
  "XmlRpc::XmlRpcServerMethod::XmlRpcServerMethod(std::string const&, XmlRpc::XmlRpcServer_)", referenced from:
      ros::XMLRPCCallWrapper::XMLRPCCallWrapper(std::string const&, boost::function<void (XmlRpc::XmlRpcValue&, XmlRpc::XmlRpcValue&)> const&, XmlRpc::XmlRpcServer_) in xmlrpc_manager.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [../../devel_isolated/roscpp/lib/libroscpp.dylib] Error 1
make[1]: **\* [CMakeFiles/roscpp.dir/all] Error 2
make: **\* [all] Error 2
jf:roscpp jelleferinga$ 

:info:build -- Build files have been written to: /opt/local/var/macports/build/_Users_jelleferinga_GIT_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated/roscpp
:info:build ==> make -j8 -l8 in '/opt/local/var/macports/build/_Users_jelleferinga_GIT_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated/roscpp'
:info:build <== Failed to process package 'roscpp': 
:info:build   Command 'make -j8 -l8' returned non-zero exit status 2
:info:build 
:info:build Reproduce this error by running:
:info:build ==> cd /opt/local/var/macports/build/_Users_jelleferinga_GIT_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated/roscpp && make -j8 -l8
:info:build 
:info:build Command failed, exiting.
:info:build Command failed: DESTDIR=/opt/local/var/macports/build/_Users_jelleferinga_GIT_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/destroot /opt/local/bin/catkin_make_isolated  --source /opt/local/var/macports/build/_Users_jelleferinga_GIT_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0  --build /opt/local/var/macports/build/_Users_jelleferinga_GIT_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated  --devel /opt/local/var/macports/build/_Users_jelleferinga_GIT_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/devel_isolated  -DCMAKE_SKIP_RPATH:BOOL=OFF  -DCMAKE_INSTALL_NAME_DIR:STRING=/opt/local/lib  -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON  -DSETUPTOOLS_DEB_LAYOUT=OFF  -DPYTHON_EXECUTABLE:FILEPATH=/opt/local/bin/python2.7  --install-space=/opt/local  --install

**Comment by kyonifer** [comment] 2014-01-02 13:25
Thanks for the update. Looks like the common factor here is ML. I'll see if i can get a copy installed on a VM and reproduce.

**Comment by jf---** [comment] 2014-01-02 13:32
Ai, that's pretty nasty. 
Sorry to hear that...

Strange though, you'd figure its something to do with the compiler / linker rather than the OS itself?
Is llvm 5.(?) the default compiler on 10.9?

**Comment by kyonifer** [comment] 2014-01-02 13:45
The XCode releases are tied to the OS releases. In particular, Apple removed the llvm-gcc front-end in Mavericks, so now "gcc" is just a symlink to clang. Depending on whats causing the linking issue (the full log would probably provide some insight) we may have to force a different compiler (e.g. macports gcc), but this has caused problems with other ports (libstdc++ vs libc++ incompatibility, among others). So it is probably easiest if I'm able to reproduce it locally. I'd bet that the issue goes away on Mavericks though, since there are a few people running roscpp with no issues there.

**Comment by yamokosk** [comment] 2014-01-02 23:37
Trying to upgrade to Mavericks... some bullshit organization bloatware that I am running into. Sounds like that is my workaround unless this is resolved.

**Comment by venabled** [comment] 2014-01-03 00:01
@kyonifer our portfile for ros-xmlrpc has a hangover effect from when we were investigating the libc++ vs libstd++ deal in Mavericks/ML. 

@yamokosk can you go ahead and nuke line 57:

```
-DCMAKE_CXX_FLAGS=-stdlib=libc++ \
```

Save that, and try your sudo ros port command again.

**Comment by yamokosk** [comment] 2014-01-03 15:50
Huzzah! That was it. Thanks! Specifically that was line 57 of the Portfile for the ros-hydro-xmlrpcpp port. I grep'ed looking for "stdlib=libc++" and didn't find it anywhere else.

Also, big thank you to you all for all the help and doing the work to keep this port going. Thanks again!

**Comment by jf---** [comment] 2014-01-03 16:07
Seconded! Amazing find thanks Don.
Ran sudo port uninstall ros-hydro-\* than  sudo port install ros-hydro-roslaunch --- _flawless_
Thanks so much!

**Comment by venabled** [comment] 2014-01-03 16:08
Do you mind submitting a pull request to close this out?

**Comment by yamokosk** [comment] 2014-01-03 16:24
Done.. #10

**Comment by kyonifer** [comment] 2014-01-03 16:35
Glad its resolved. Looks like its yet another episode of the ongoing saga of libstdc++ vs libc++...
I'll go ahead and update the build scripts to strip that line (which hopefully doesnt break anything on Mavericks...)

**Comment by kyonifer** [comment] 2014-01-03 17:04
Commited pull request and closing.

**Closed as completed by kyonifer** 2014-01-03 17:04 UTC
